# SPDX-License-Identifier: MIT
#
# Copyright (c) 2014-2026 FPGA Ninja, LLC
#
# Authors:
# - Alex Forencich
#

# XDC constraints for the BittWare XUSP3S board
# part: xcvu095-ffvb2104-2-e

# 100 MHz DDR4 B clock from Si5338 A ch 2
set_property -dict {LOC E38  IOSTANDARD DIFF_SSTL12_DCI ODT RTT_48} [get_ports clk_ddr_b_p]
set_property -dict {LOC D38  IOSTANDARD DIFF_SSTL12_DCI ODT RTT_48} [get_ports clk_ddr_b_n]
create_clock -period 10.000 -name clk_ddr_b [get_ports clk_ddr_b_p]

# DDR4 B (U22, U23, U24, U25, U26, U79, U80, U81, U82)
# 9x MT40A512M8RH-083E
set_property -dict {LOC A37  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_adr[0]}]
set_property -dict {LOC A38  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_adr[1]}]
set_property -dict {LOC B35  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_adr[2]}]
set_property -dict {LOC A35  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_adr[3]}]
set_property -dict {LOC E35  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_adr[4]}]
set_property -dict {LOC D35  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_adr[5]}]
set_property -dict {LOC E37  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_adr[6]}]
set_property -dict {LOC B34  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_adr[7]}]
set_property -dict {LOC A34  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_adr[8]}]
set_property -dict {LOC D34  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_adr[9]}]
set_property -dict {LOC C34  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_adr[10]}]
set_property -dict {LOC D33  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_adr[11]}]
set_property -dict {LOC C33  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_adr[12]}]
set_property -dict {LOC C32  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_adr[13]}]
set_property -dict {LOC B32  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_adr[14]}]
set_property -dict {LOC D31  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_adr[15]}]
set_property -dict {LOC C31  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_adr[16]}]
set_property -dict {LOC C36  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_ba[0]}]
set_property -dict {LOC C37  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_ba[1]}]
set_property -dict {LOC E36  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_bg[0]}]
set_property -dict {LOC D36  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_bg[1]}]
set_property -dict {LOC B36  IOSTANDARD DIFF_SSTL12_DCI } [get_ports {ddr4_b_ck_t[0]}]
set_property -dict {LOC B37  IOSTANDARD DIFF_SSTL12_DCI } [get_ports {ddr4_b_ck_c[0]}]
set_property -dict {LOC A40  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_cke[0]}]
set_property -dict {LOC D39  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_cs_n[0]}]
set_property -dict {LOC F38  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_act_n}]
set_property -dict {LOC A39  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_odt[0]}]
set_property -dict {LOC C39  IOSTANDARD SSTL12_DCI      } [get_ports {ddr4_b_par}]
set_property -dict {LOC E40  IOSTANDARD LVCMOS12 DRIVE 8} [get_ports {ddr4_b_reset_n}]

set_property -dict {LOC E33  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[0]}]
set_property -dict {LOC F33  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[1]}]
set_property -dict {LOC E32  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[2]}]
set_property -dict {LOC F32  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[3]}]
set_property -dict {LOC G32  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[4]}]
set_property -dict {LOC H32  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[5]}]
set_property -dict {LOC G31  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[6]}]
set_property -dict {LOC H31  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[7]}]
set_property -dict {LOC K33  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[8]}]
set_property -dict {LOC L33  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[9]}]
set_property -dict {LOC J31  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[10]}]
set_property -dict {LOC K31  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[11]}]
set_property -dict {LOC L30  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[12]}]
set_property -dict {LOC M30  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[13]}]
set_property -dict {LOC K32  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[14]}]
set_property -dict {LOC L32  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[15]}]
set_property -dict {LOC N33  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[16]}]
set_property -dict {LOC N32  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[17]}]
set_property -dict {LOC N31  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[18]}]
set_property -dict {LOC P31  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[19]}]
set_property -dict {LOC N34  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[20]}]
set_property -dict {LOC P34  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[21]}]
set_property -dict {LOC R32  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[22]}]
set_property -dict {LOC R31  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[23]}]
set_property -dict {LOC T30  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[24]}]
set_property -dict {LOC U30  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[25]}]
set_property -dict {LOC U31  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[26]}]
set_property -dict {LOC V31  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[27]}]
set_property -dict {LOC T32  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[28]}]
set_property -dict {LOC U32  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[29]}]
set_property -dict {LOC R33  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[30]}]
set_property -dict {LOC T33  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[31]}]
set_property -dict {LOC A30  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[32]}]
set_property -dict {LOC B30  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[33]}]
set_property -dict {LOC A29  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[34]}]
set_property -dict {LOC B29  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[35]}]
set_property -dict {LOC D30  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[36]}]
set_property -dict {LOC E30  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[37]}]
set_property -dict {LOC C29  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[38]}]
set_property -dict {LOC D29  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[39]}]
set_property -dict {LOC D28  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[40]}]
set_property -dict {LOC E28  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[41]}]
set_property -dict {LOC E27  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[42]}]
set_property -dict {LOC F27  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[43]}]
set_property -dict {LOC G29  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[44]}]
set_property -dict {LOC H29  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[45]}]
set_property -dict {LOC G27  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[46]}]
set_property -dict {LOC G26  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[47]}]
set_property -dict {LOC J29  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[48]}]
set_property -dict {LOC J28  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[49]}]
set_property -dict {LOC H28  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[50]}]
set_property -dict {LOC H27  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[51]}]
set_property -dict {LOC L27  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[52]}]
set_property -dict {LOC M27  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[53]}]
set_property -dict {LOC K28  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[54]}]
set_property -dict {LOC L28  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[55]}]
set_property -dict {LOC N26  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[56]}]
set_property -dict {LOC P26  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[57]}]
set_property -dict {LOC N28  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[58]}]
set_property -dict {LOC P28  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[59]}]
set_property -dict {LOC R26  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[60]}]
set_property -dict {LOC T26  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[61]}]
set_property -dict {LOC R27  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[62]}]
set_property -dict {LOC T27  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[63]}]
set_property -dict {LOC F35  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[64]}]
set_property -dict {LOC F34  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[65]}]
set_property -dict {LOC G34  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[66]}]
set_property -dict {LOC H34  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[67]}]
set_property -dict {LOC J36  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[68]}]
set_property -dict {LOC J35  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[69]}]
set_property -dict {LOC F37  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[70]}]
set_property -dict {LOC G37  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dq[71]}]
set_property -dict {LOC J33  IOSTANDARD DIFF_POD12_DCI  } [get_ports {ddr4_b_dqs_t[0]}]
set_property -dict {LOC H33  IOSTANDARD DIFF_POD12_DCI  } [get_ports {ddr4_b_dqs_c[0]}]
set_property -dict {LOC K30  IOSTANDARD DIFF_POD12_DCI  } [get_ports {ddr4_b_dqs_t[1]}]
set_property -dict {LOC J30  IOSTANDARD DIFF_POD12_DCI  } [get_ports {ddr4_b_dqs_c[1]}]
set_property -dict {LOC M34  IOSTANDARD DIFF_POD12_DCI  } [get_ports {ddr4_b_dqs_t[2]}]
set_property -dict {LOC L34  IOSTANDARD DIFF_POD12_DCI  } [get_ports {ddr4_b_dqs_c[2]}]
set_property -dict {LOC V32  IOSTANDARD DIFF_POD12_DCI  } [get_ports {ddr4_b_dqs_t[3]}]
set_property -dict {LOC V33  IOSTANDARD DIFF_POD12_DCI  } [get_ports {ddr4_b_dqs_c[3]}]
set_property -dict {LOC A27  IOSTANDARD DIFF_POD12_DCI  } [get_ports {ddr4_b_dqs_t[4]}]
set_property -dict {LOC A28  IOSTANDARD DIFF_POD12_DCI  } [get_ports {ddr4_b_dqs_c[4]}]
set_property -dict {LOC F28  IOSTANDARD DIFF_POD12_DCI  } [get_ports {ddr4_b_dqs_t[5]}]
set_property -dict {LOC F29  IOSTANDARD DIFF_POD12_DCI  } [get_ports {ddr4_b_dqs_c[5]}]
set_property -dict {LOC K26  IOSTANDARD DIFF_POD12_DCI  } [get_ports {ddr4_b_dqs_t[6]}]
set_property -dict {LOC K27  IOSTANDARD DIFF_POD12_DCI  } [get_ports {ddr4_b_dqs_c[6]}]
set_property -dict {LOC P29  IOSTANDARD DIFF_POD12_DCI  } [get_ports {ddr4_b_dqs_t[7]}]
set_property -dict {LOC N29  IOSTANDARD DIFF_POD12_DCI  } [get_ports {ddr4_b_dqs_c[7]}]
set_property -dict {LOC H36  IOSTANDARD DIFF_POD12_DCI  } [get_ports {ddr4_b_dqs_t[8]}]
set_property -dict {LOC G36  IOSTANDARD DIFF_POD12_DCI  } [get_ports {ddr4_b_dqs_c[8]}]
set_property -dict {LOC G30  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dm_dbi_n[0]}]
set_property -dict {LOC M31  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dm_dbi_n[1]}]
set_property -dict {LOC R30  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dm_dbi_n[2]}]
set_property -dict {LOC U34  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dm_dbi_n[3]}]
set_property -dict {LOC C27  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dm_dbi_n[4]}]
set_property -dict {LOC J26  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dm_dbi_n[5]}]
set_property -dict {LOC M29  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dm_dbi_n[6]}]
set_property -dict {LOC T28  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dm_dbi_n[7]}]
set_property -dict {LOC H37  IOSTANDARD POD12_DCI       } [get_ports {ddr4_b_dm_dbi_n[8]}]
