# SPDX-License-Identifier: MIT
#
# Copyright (c) 2014-2026 FPGA Ninja, LLC
#
# Authors:
# - Alex Forencich
#

# XDC constraints for the fb2CG@KU15P
# part: xcku15p-ffve1760-2-e

# DDR4 C2
# 5x K4A8G165WB-BCTD / MT40A512M16HA-075E
set_property -dict {LOC J30  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_adr[0]}]
set_property -dict {LOC J29  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_adr[1]}]
set_property -dict {LOC G32  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_adr[2]}]
set_property -dict {LOC F31  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_adr[3]}]
set_property -dict {LOC H29  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_adr[4]}]
set_property -dict {LOC F28  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_adr[5]}]
set_property -dict {LOC J28  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_adr[6]}]
set_property -dict {LOC H32  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_adr[7]}]
set_property -dict {LOC L29  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_adr[8]}]
set_property -dict {LOC H31  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_adr[9]}]
set_property -dict {LOC F30  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_adr[10]}]
set_property -dict {LOC J32  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_adr[11]}]
set_property -dict {LOC B28  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_adr[12]}]
set_property -dict {LOC K32  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_adr[13]}]
set_property -dict {LOC F29  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_adr[14]}]
set_property -dict {LOC D29  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_adr[15]}]
set_property -dict {LOC C32  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_adr[16]}]
set_property -dict {LOC G31  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_ba[0]}]
set_property -dict {LOC H30  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_ba[1]}]
set_property -dict {LOC E31  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_bg[0]}]
set_property -dict {LOC D30  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_bg[1]}]
set_property -dict {LOC E32  IOSTANDARD DIFF_SSTL12_DCI} [get_ports {ddr4_c2_ck_t}]
set_property -dict {LOC D32  IOSTANDARD DIFF_SSTL12_DCI} [get_ports {ddr4_c2_ck_c}]
set_property -dict {LOC E30  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_cke}]
set_property -dict {LOC C31  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_cs_n}]
set_property -dict {LOC E28  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_act_n}]
set_property -dict {LOC D28  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_odt}]
set_property -dict {LOC J18  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c2_par}]
set_property -dict {LOC L19  IOSTANDARD LVCMOS12       } [get_ports {ddr4_c2_reset_n}]
set_property -dict {LOC F19  IOSTANDARD LVCMOS12       } [get_ports {ddr4_c2_alert_n}]
set_property -dict {LOC E15  IOSTANDARD LVCMOS12       } [get_ports {ddr4_c2_ten}]

set_property -dict {LOC G38  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[0]}]
set_property -dict {LOC D42  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[1]}]
set_property -dict {LOC F39  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[2]}]
set_property -dict {LOC G41  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[3]}]
set_property -dict {LOC F38  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[4]}]
set_property -dict {LOC G42  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[5]}]
set_property -dict {LOC G39  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[6]}]
set_property -dict {LOC E42  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[7]}]
set_property -dict {LOC C39  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[8]}]
set_property -dict {LOC B41  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[9]}]
set_property -dict {LOC B39  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[10]}]
set_property -dict {LOC C41  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[11]}]
set_property -dict {LOC B38  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[12]}]
set_property -dict {LOC C42  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[13]}]
set_property -dict {LOC A38  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[14]}]
set_property -dict {LOC C40  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[15]}]
set_property -dict {LOC AT36 IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[16]}]
set_property -dict {LOC AR38 IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[17]}]
set_property -dict {LOC AP36 IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[18]}]
set_property -dict {LOC AR37 IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[19]}]
set_property -dict {LOC AR36 IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[20]}]
set_property -dict {LOC AP39 IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[21]}]
set_property -dict {LOC AP37 IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[22]}]
set_property -dict {LOC AP40 IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[23]}]
set_property -dict {LOC N24  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[24]}]
set_property -dict {LOC M26  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[25]}]
set_property -dict {LOC N26  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[26]}]
set_property -dict {LOC L25  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[27]}]
set_property -dict {LOC N25  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[28]}]
set_property -dict {LOC L26  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[29]}]
set_property -dict {LOC M23  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[30]}]
set_property -dict {LOC L23  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[31]}]
set_property -dict {LOC AP41 IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[32]}]
set_property -dict {LOC AT41 IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[33]}]
set_property -dict {LOC AP42 IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[34]}]
set_property -dict {LOC AU40 IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[35]}]
set_property -dict {LOC AR41 IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[36]}]
set_property -dict {LOC AV40 IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[37]}]
set_property -dict {LOC AR42 IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[38]}]
set_property -dict {LOC AT40 IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[39]}]
set_property -dict {LOC K28  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[40]}]
set_property -dict {LOC K31  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[41]}]
set_property -dict {LOC P28  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[42]}]
set_property -dict {LOC N28  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[43]}]
set_property -dict {LOC M27  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[44]}]
set_property -dict {LOC L31  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[45]}]
set_property -dict {LOC N27  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[46]}]
set_property -dict {LOC L28  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[47]}]
set_property -dict {LOC D34  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[48]}]
set_property -dict {LOC A34  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[49]}]
set_property -dict {LOC C34  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[50]}]
set_property -dict {LOC A35  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[51]}]
set_property -dict {LOC C36  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[52]}]
set_property -dict {LOC A36  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[53]}]
set_property -dict {LOC C37  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[54]}]
set_property -dict {LOC B34  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[55]}]
set_property -dict {LOC B29  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[56]}]
set_property -dict {LOC B33  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[57]}]
set_property -dict {LOC A29  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[58]}]
set_property -dict {LOC B32  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[59]}]
set_property -dict {LOC A28  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[60]}]
set_property -dict {LOC A33  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[61]}]
set_property -dict {LOC C29  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[62]}]
set_property -dict {LOC B31  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[63]}]
set_property -dict {LOC E37  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[64]}]
set_property -dict {LOC E36  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[65]}]
set_property -dict {LOC F36  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[66]}]
set_property -dict {LOC D37  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[67]}]
set_property -dict {LOC E38  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[68]}]
set_property -dict {LOC F33  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[69]}]
set_property -dict {LOC G36  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[70]}]
set_property -dict {LOC E33  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dq[71]}]
set_property -dict {LOC F41  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c2_dqs_t[0]}]
set_property -dict {LOC E41  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c2_dqs_c[0]}]
set_property -dict {LOC A39  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c2_dqs_t[1]}]
set_property -dict {LOC A40  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c2_dqs_c[1]}]
set_property -dict {LOC AT37 IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c2_dqs_t[2]}]
set_property -dict {LOC AU38 IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c2_dqs_c[2]}]
set_property -dict {LOC M24  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c2_dqs_t[3]}]
set_property -dict {LOC L24  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c2_dqs_c[3]}]
set_property -dict {LOC AT42 IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c2_dqs_t[4]}]
set_property -dict {LOC AU42 IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c2_dqs_c[4]}]
set_property -dict {LOC L30  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c2_dqs_t[5]}]
set_property -dict {LOC K30  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c2_dqs_c[5]}]
set_property -dict {LOC B36  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c2_dqs_t[6]}]
set_property -dict {LOC B37  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c2_dqs_c[6]}]
set_property -dict {LOC A30  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c2_dqs_t[7]}]
set_property -dict {LOC A31  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c2_dqs_c[7]}]
set_property -dict {LOC F35  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c2_dqs_t[8]}]
set_property -dict {LOC E35  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c2_dqs_c[8]}]
set_property -dict {LOC G40  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dm_dbi_n[0]}]
set_property -dict {LOC D39  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dm_dbi_n[1]}]
set_property -dict {LOC AP38 IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dm_dbi_n[2]}]
set_property -dict {LOC P23  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dm_dbi_n[3]}]
set_property -dict {LOC AT39 IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dm_dbi_n[4]}]
set_property -dict {LOC M28  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dm_dbi_n[5]}]
set_property -dict {LOC D35  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dm_dbi_n[6]}]
set_property -dict {LOC C30  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dm_dbi_n[7]}]
set_property -dict {LOC G34  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c2_dm_dbi_n[8]}]
