# SPDX-License-Identifier: MIT
#
# Copyright (c) 2014-2026 FPGA Ninja, LLC
#
# Authors:
# - Alex Forencich
#

# XDC constraints for the fb2CG@KU15P
# part: xcku15p-ffve1760-2-e

# DDR4 C3
# 5x K4A8G165WB-BCTD / MT40A512M16HA-075E
set_property -dict {LOC F23  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_adr[0]}]
set_property -dict {LOC G23  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_adr[1]}]
set_property -dict {LOC H24  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_adr[2]}]
set_property -dict {LOC F25  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_adr[3]}]
set_property -dict {LOC F26  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_adr[4]}]
set_property -dict {LOC F24  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_adr[5]}]
set_property -dict {LOC K26  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_adr[6]}]
set_property -dict {LOC G27  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_adr[7]}]
set_property -dict {LOC J27  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_adr[8]}]
set_property -dict {LOC G24  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_adr[9]}]
set_property -dict {LOC E25  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_adr[10]}]
set_property -dict {LOC H27  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_adr[11]}]
set_property -dict {LOC E23  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_adr[12]}]
set_property -dict {LOC G26  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_adr[13]}]
set_property -dict {LOC J23  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_adr[14]}]
set_property -dict {LOC D23  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_adr[15]}]
set_property -dict {LOC B27  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_adr[16]}]
set_property -dict {LOC J25  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_ba[0]}]
set_property -dict {LOC K25  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_ba[1]}]
set_property -dict {LOC J24  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_bg[0]}]
set_property -dict {LOC D25  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_bg[1]}]
set_property -dict {LOC E27  IOSTANDARD DIFF_SSTL12_DCI} [get_ports {ddr4_c3_ck_t}]
set_property -dict {LOC D27  IOSTANDARD DIFF_SSTL12_DCI} [get_ports {ddr4_c3_ck_c}]
set_property -dict {LOC E26  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_cke}]
set_property -dict {LOC H25  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_cs_n}]
set_property -dict {LOC D24  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_act_n}]
set_property -dict {LOC B22  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_odt}]
set_property -dict {LOC A14  IOSTANDARD SSTL12_DCI     } [get_ports {ddr4_c3_par}]
set_property -dict {LOC M16  IOSTANDARD LVCMOS12       } [get_ports {ddr4_c3_reset_n}]
set_property -dict {LOC F20  IOSTANDARD LVCMOS12       } [get_ports {ddr4_c3_alert_n}]
set_property -dict {LOC J17  IOSTANDARD LVCMOS12       } [get_ports {ddr4_c3_ten}]

set_property -dict {LOC E18  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[0]}]
set_property -dict {LOC G17  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[1]}]
set_property -dict {LOC F16  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[2]}]
set_property -dict {LOC G16  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[3]}]
set_property -dict {LOC E16  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[4]}]
set_property -dict {LOC H17  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[5]}]
set_property -dict {LOC E17  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[6]}]
set_property -dict {LOC F18  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[7]}]
set_property -dict {LOC N12  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[8]}]
set_property -dict {LOC P15  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[9]}]
set_property -dict {LOC M13  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[10]}]
set_property -dict {LOC P12  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[11]}]
set_property -dict {LOC M12  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[12]}]
set_property -dict {LOC N15  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[13]}]
set_property -dict {LOC M14  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[14]}]
set_property -dict {LOC P13  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[15]}]
set_property -dict {LOC C17  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[16]}]
set_property -dict {LOC C15  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[17]}]
set_property -dict {LOC A16  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[18]}]
set_property -dict {LOC A15  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[19]}]
set_property -dict {LOC B17  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[20]}]
set_property -dict {LOC D15  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[21]}]
set_property -dict {LOC D18  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[22]}]
set_property -dict {LOC D17  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[23]}]
set_property -dict {LOC J14  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[24]}]
set_property -dict {LOC L16  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[25]}]
set_property -dict {LOC H15  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[26]}]
set_property -dict {LOC H14  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[27]}]
set_property -dict {LOC J15  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[28]}]
set_property -dict {LOC K16  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[29]}]
set_property -dict {LOC K15  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[30]}]
set_property -dict {LOC H16  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[31]}]
set_property -dict {LOC K21  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[32]}]
set_property -dict {LOC H19  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[33]}]
set_property -dict {LOC J20  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[34]}]
set_property -dict {LOC J19  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[35]}]
set_property -dict {LOC K20  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[36]}]
set_property -dict {LOC K18  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[37]}]
set_property -dict {LOC H20  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[38]}]
set_property -dict {LOC L18  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[39]}]
set_property -dict {LOC D20  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[40]}]
set_property -dict {LOC B19  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[41]}]
set_property -dict {LOC A21  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[42]}]
set_property -dict {LOC A19  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[43]}]
set_property -dict {LOC B21  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[44]}]
set_property -dict {LOC D19  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[45]}]
set_property -dict {LOC C21  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[46]}]
set_property -dict {LOC A20  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[47]}]
set_property -dict {LOC N19  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[48]}]
set_property -dict {LOC N22  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[49]}]
set_property -dict {LOC P20  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[50]}]
set_property -dict {LOC N21  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[51]}]
set_property -dict {LOC P19  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[52]}]
set_property -dict {LOC N20  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[53]}]
set_property -dict {LOC P18  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[54]}]
set_property -dict {LOC P22  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[55]}]
set_property -dict {LOC C25  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[56]}]
set_property -dict {LOC A23  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[57]}]
set_property -dict {LOC B26  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[58]}]
set_property -dict {LOC A26  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[59]}]
set_property -dict {LOC C26  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[60]}]
set_property -dict {LOC C24  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[61]}]
set_property -dict {LOC A24  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[62]}]
set_property -dict {LOC A25  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[63]}]
set_property -dict {LOC H22  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[64]}]
set_property -dict {LOC E21  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[65]}]
set_property -dict {LOC G21  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[66]}]
set_property -dict {LOC E22  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[67]}]
set_property -dict {LOC H21  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[68]}]
set_property -dict {LOC E20  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[69]}]
set_property -dict {LOC G22  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[70]}]
set_property -dict {LOC D22  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dq[71]}]
set_property -dict {LOC G14  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c3_dqs_t[0]}]
set_property -dict {LOC F14  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c3_dqs_c[0]}]
set_property -dict {LOC P14  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c3_dqs_t[1]}]
set_property -dict {LOC N14  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c3_dqs_c[1]}]
set_property -dict {LOC C16  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c3_dqs_t[2]}]
set_property -dict {LOC B16  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c3_dqs_c[2]}]
set_property -dict {LOC L15  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c3_dqs_t[3]}]
set_property -dict {LOC L14  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c3_dqs_c[3]}]
set_property -dict {LOC K22  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c3_dqs_t[4]}]
set_property -dict {LOC J22  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c3_dqs_c[4]}]
set_property -dict {LOC C20  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c3_dqs_t[5]}]
set_property -dict {LOC C19  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c3_dqs_c[5]}]
set_property -dict {LOC M21  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c3_dqs_t[6]}]
set_property -dict {LOC L21  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c3_dqs_c[6]}]
set_property -dict {LOC B23  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c3_dqs_t[7]}]
set_property -dict {LOC B24  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c3_dqs_c[7]}]
set_property -dict {LOC G19  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c3_dqs_t[8]}]
set_property -dict {LOC G18  IOSTANDARD DIFF_POD12_DCI } [get_ports {ddr4_c3_dqs_c[8]}]
set_property -dict {LOC F15  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dm_dbi_n[0]}]
set_property -dict {LOC N16  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dm_dbi_n[1]}]
set_property -dict {LOC B14  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dm_dbi_n[2]}]
set_property -dict {LOC K17  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dm_dbi_n[3]}]
set_property -dict {LOC L20  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dm_dbi_n[4]}]
set_property -dict {LOC B18  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dm_dbi_n[5]}]
set_property -dict {LOC M19  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dm_dbi_n[6]}]
set_property -dict {LOC C27  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dm_dbi_n[7]}]
set_property -dict {LOC F21  IOSTANDARD POD12_DCI      } [get_ports {ddr4_c3_dm_dbi_n[8]}]
